-- 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS;

-- 역순 정렬하기 (오름차순 ASC(생략가능) / 내림차순 DESC)
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

-- 아픈 동물 찾기(조건 WHERE)
-- and, or, not, like : MYSQL은 와일드 카드로 %, ORACLE은 *
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'Sick';

-- 어린 동물 찾기(조건 WHERE)
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != 'Aged';

-- 동물의 아이디와 이름 / default 순서는 오름차순 정렬
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS;

-- 여러 기준으로 정렬하기(ORDER BY 뒤 콤마로 기준 구분)
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME, DATETIME DESC;

-- 상위 n개 레코드(LIMIT으로 상위 N개 추출)
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;